name: goh_vote_md
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  add_2_calendar: ^3.0.1
  intl: ^0.20.2
  http: ^1.5.0
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^9.1.2
  dotted_border: ^2.1.0
  mailer: ^6.5.0
  font_awesome_flutter: ^10.9.1
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/title_logo.png
    - assets/top_maryland.png
    - assets/icon.png
    - assets/dropbox.csv
    - assets/early.csv
    - assets/contacts.csv

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
